# Generated by Django 6.0.2 on 2026-02-13 17:31

import storage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        max_length=255, verbose_name="Оригинальное имя файла"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=storage.models.upload_to, verbose_name="Файл"
                    ),
                ),
                ("size", models.BigIntegerField(verbose_name="Размер файла (байт)")),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME тип"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "last_downloaded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последнего скачивания"
                    ),
                ),
                (
                    "share_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="Токен для шеринга",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичный файл"),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, verbose_name="Количество скачиваний"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удален"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата удаления"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название папки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
                "ordering": ["name"],
            },
        ),
    ]
