# Generated by Django 6.0.2 on 2026-02-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="mime_type",
            field=models.CharField(
                blank=True,
                default="application/octet-stream",
                max_length=100,
                verbose_name="MIME тип",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="size",
            field=models.BigIntegerField(default=0, verbose_name="Размер файла (байт)"),
        ),
    ]
